# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7873340d70ba12c55d127b94752ef7b764c27fcda6d14823225a45eb054535a9b51e4ba2e6e1edca7bf1584175fac5ca346fcc17c97185c9421069858d1e3d79

test:
  secret_key_base: 73e5c4ebc33eaf07b06d4c8a162d7cf0f4fb9d74174ac1c65fa22a58188bcca7a7f5b39b479f812328632e91f48a9bb63d26f43257187faf8c2b833368fd59e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
